default: &default
  adapter: postgis
  host: localhost
  port: 5433
  password: postgres
  username: postgres
  schema_search_path: public
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: delivery_api_development

test:
  <<: *default
  database: delivery_api_test

production:
  <<: *default
  url: "postgres://postgres:postgres@localhost/delivery_api_production"
  database: delivery_api_production
